// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgzhBlHVjmQEJ43kgmEW3jbraT5DNQz0Y',
    appId: '1:108927420628:web:b378e39c325d505f401341',
    messagingSenderId: '108927420628',
    projectId: 'primejetmobile-83583',
    authDomain: 'primejetmobile-83583.firebaseapp.com',
    storageBucket: 'primejetmobile-83583.firebasestorage.app',
    measurementId: 'G-8NW17Y3P87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPV-KhAIIegC-C9xNkviDbRL5mE8beAyI',
    appId: '1:108927420628:android:e486ba39320fdb2b401341',
    messagingSenderId: '108927420628',
    projectId: 'primejetmobile-83583',
    storageBucket: 'primejetmobile-83583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7fjJItbWvh4PFWyTmiH0o_JrPFkvJME',
    appId: '1:108927420628:ios:145c5136aca970c9401341',
    messagingSenderId: '108927420628',
    projectId: 'primejetmobile-83583',
    storageBucket: 'primejetmobile-83583.firebasestorage.app',
    androidClientId: '108927420628-6g6ikd329uatfbnrbde5bhvrhhp6t8oq.apps.googleusercontent.com',
    iosClientId: '108927420628-0tpfap0aei70115vkqhvii7soqfn1j35.apps.googleusercontent.com',
    iosBundleId: 'com.example.primejetMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI7fjJItbWvh4PFWyTmiH0o_JrPFkvJME',
    appId: '1:108927420628:ios:145c5136aca970c9401341',
    messagingSenderId: '108927420628',
    projectId: 'primejetmobile-83583',
    storageBucket: 'primejetmobile-83583.firebasestorage.app',
    androidClientId: '108927420628-6g6ikd329uatfbnrbde5bhvrhhp6t8oq.apps.googleusercontent.com',
    iosClientId: '108927420628-0tpfap0aei70115vkqhvii7soqfn1j35.apps.googleusercontent.com',
    iosBundleId: 'com.example.primejetMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgzhBlHVjmQEJ43kgmEW3jbraT5DNQz0Y',
    appId: '1:108927420628:web:51ada23e9a4c01bc401341',
    messagingSenderId: '108927420628',
    projectId: 'primejetmobile-83583',
    authDomain: 'primejetmobile-83583.firebaseapp.com',
    storageBucket: 'primejetmobile-83583.firebasestorage.app',
    measurementId: 'G-H1J45RZS9M',
  );

}